const portfolio = [
    {   "id": "wpw1",
        "categories": ["wordpress-site"],
        "screenshotURL": "/assets/wordpress/foto-by-silvia-desktop-calla.png",
        "otherAssets": ["/assets/wordpress/fotobysilvia-gallery.jpg", "/assets/wordpress/fotobysilvia-desktop.jpg",],
        "title": "Foto by Silvia",
        "subTitle": "WordPress Custom Theme",
        "problem": "The client is a photographer who was less concerned about finding new customers; referring viewers from shows and providing a portfolio for clients and gallery owners was her main concern. In addition, she wanted to keep written material to a minimum, because her clients are international.",
        "approach": "Working in a visual medium, the look of the website was very important to the client. As her business was new, I wanted to create a webiste that could grow and change with her business. She was new to administering websites as well, so I knew I needed to create a backend that she could learn to use herself with confidence, without having to go down rabbit-holes of image adjustment.",
        "results": "",
        "link": ""
    },
    {   "id": "wpw2",
        "categories": ["wordpress-site"],
        "screenshotURL": "/assets/wordpress/advocate-law-desktop-top.jpg",
        "otherAssets": ["/assets/wordpress/advocate-law-desktop-top.jpg"],
        "title": "Advocate Law",
        "subTitle": "Custom-Built WP Genesis Child Theme",
        "problem": "",
        "approach": "",
        "results": "",
        "link": ""
    },
    {   "id": "wpw3",
        "categories": ["wordpress-site"],
        "screenshotURL": "/assets/wordpress/armour-auto-hero-scrnshot.jpg",
        "otherAssets": ["/assets/wordpress/armour-auto-desktop-opt.jpg", "/assets/wordpress/armour-auto-desktop-block-open.jpg", "/assets/wordpress/armour-auto-mobile-block-open.jpg"],
        "title": "Armour Auto",
        "subTitle": "From Scratch Animation for Custom-Bult WP Theme from Company Blocks",
        "problem": "The designer wanted to give the client a modern website with animations that our company didn't yet have.",
        "approach": "Out three-person team needed to design two new blocks, one with flip panels with links to services, and the second, a contact block which expands to show contact information",
        "results": "Please see the website.",
        "link": "https://armorautodetailing.com/"
    },
    {   "id": "wpw4",
        "categories": ["wordpress-site"],
        "screenshotURL": "/assets/wordpress/ageless-beauty-hero-scrnshot-opt.jpg",
        "otherAssets": ["assets/wordpress/ageless-beauty-desktop.jpg", "/assets/wordpress/ageless-beauty-desktop-opt.jpg"],
        "title": "Ageless Beauty",
        "subTitle": "Custom-built WP theme from company blocks",
        "problem": "I needed to build two new blocks - one to display the featured posts, with the photo and title, and an excerpt on hover, and another tat the client wanted at the last minute to seamlessly connect to her product video clips.",
        "approach": "",
        "results": "",
        "link": ""
    },
    {   "id": "wpw5",
        "categories": ["wordpress-site"],
        "screenshotURL": "/assets/wordpress/occc-screenshot.png",
        "otherAssets": [],
        "title": "Oregon Coast Comic con",
        "subTitle": "custom-built wp theme from company blocks",
        "problem": "",
        "approach": "",
        "results": "",
        "link": ""
    },
    {   "id": "wpw6",
        "categories": ["wordpress-site"],
        "screenshotURL": "/assets/wordpress/therapy-kitchen-screenshot.png",
        "otherAssets": ["/assets/wordpress/therapy-kitchen-screenshot.png"],
        "title": "Therapy Kitchen",
        "subTitle": "custom-built wp theme from company blocks",
        "problem": "",
        "approach": "",
        "results": "",
        "link": ""
    },
    {   "id": "wpp1",
        "categories": ["wordpress", "wordpress-plugin", "featured"],
        "screenshotURL": "/assets/wordpress/screenshot-plugin-cropped.jpg",
        "otherAssets": ["/assets/wordpress/screenshot-plugin.jpg", "/assets/wordpress/screenshot-plugin-indiv-page.jpg"],
        "title": "WordPress Video Posts Plugin",
        "subTitle": "Custom Video Format Posts for the Covid Period",
        "problem": "",
        "approach": "",
        "results": "",
        "link": ""
    }
]
export default portfolio